mysql:
  image: mysql
  ports:
    - "3306:3306"
  environment:
    - MYSQL_USER=root
    - MYSQL_PASSWORD=Admin@123
    - MYSQL_DATABASE=dashboarddb
    - MYSQL_ROOT_PASSWORD=Admin@123
  volumes:
    - "./conf.d:/etc/mysql/conf.d:ro"